import os
import telebot
import requests
import random
import json
import numpy as np
import textwrap
from PIL import Image, ImageDraw, ImageFont
from moviepy.editor import (
    VideoFileClip, AudioFileClip, ImageClip, CompositeVideoClip,
    concatenate_videoclips
)
import asyncio
import edge_tts

# --- AYARLAR ---
TELEGRAM_TOKEN = os.environ.get("TELEGRAM_TOKEN")
PEXELS_API_KEY = os.environ.get("PEXELS_API_KEY")
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

bot = telebot.TeleBot(TELEGRAM_TOKEN)

# YouTube Shorts için çözünürlük
W, H = 1080, 1920
FPS = 30

# --- FONT ---
def get_font():
    font_path = "Oswald-Bold.ttf"
    if not os.path.exists(font_path):
        url = "https://github.com/google/fonts/raw/main/ofl/oswald/Oswald-Bold.ttf"
        r = requests.get(url, timeout=10)
        if r.status_code == 200:
            with open(font_path, "wb") as f:
                f.write(r.content)
    return font_path

# --- TTS (edge-tts async) ---
async def generate_tts(text, out="voice.mp3", voice="en-US-GuyNeural"):
    communicate = edge_tts.Communicate(text, voice)
    try:
        await communicate.save(out)
    except Exception as e:
        print(f"TTS Hatası: {e}")
        # Hata durumunda boş dosya yerine sessiz bir dosya oluşturmuyoruz, None dönmeli
        if os.path.exists(out):
            os.remove(out)

# --- İÇERİK ÜRETİCİ (Script + Metadata) ---
def get_content(topic):
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key={GEMINI_API_KEY}"
    
    # Prompt'u JSON formatında yanıt isteyecek şekilde güncelledik
    prompt = (
        f"You are a professional YouTube Shorts creator. Create a viral scary story about '{topic}'. "
        "Output ONLY a valid JSON object with the following keys:\n"
        "- 'script': The scary story text (110-130 words, simple English, short sentences).\n"
        "- 'title': A clickbait title for the video.\n"
        "- 'description': A short engaging description for YouTube.\n"
        "- 'hashtags': A string of 5-10 popular hashtags.\n"
        "Do not write anything else, just the JSON."
    )
    
    payload = {"contents": [{"parts": [{"text": prompt}]}]}
    
    try:
        r = requests.post(url, json=payload, timeout=20)
        if r.status_code == 200:
            data = r.json()
            raw_text = data['candidates'][0]['content']['parts'][0]['text']
            # Markdown formatını temizle (bazı modeller ```json ... ``` ekler)
            raw_text = raw_text.replace("```json", "").replace("```", "").strip()
            return json.loads(raw_text)
        else:
            print(f"Gemini API Hatası: {r.status_code} - {r.text}")
    except Exception as e:
        print(f"Bağlantı Hatası: {e}")

    # Fallback (Hata olursa dönecek varsayılan değerler)
    return {
        "script": "I looked at my phone. It showed my face. But I was not holding it. Someone was behind me.",
        "title": "Creepy Glitch 😱",
        "description": "Short horror story generated by bot.",
        "hashtags": "#horror #shorts #scary"
    }

# --- VIDEO BUL ---
def get_videos(total_duration):
    headers = {"Authorization": PEXELS_API_KEY}
    queries = ["dark hallway", "creepy room", "abandoned house", "night corridor", "horror atmosphere", "shadows"]
    random.shuffle(queries)

    paths = []
    current = 0
    i = 0

    for q in queries:
        if current >= total_duration:
            break

        url = f"https://api.pexels.com/videos/search?query={q}&per_page=5&orientation=portrait"
        try:
            r = requests.get(url, headers=headers, timeout=15)
            data = r.json().get("videos", [])
        except:
            continue

        for v in data:
            if current >= total_duration:
                break
            
            # En uygun video linkini bul
            video_files = v.get("video_files", [])
            if not video_files: continue
            
            # HD kaliteye yakın olanı seçmeye çalış
            link = max(video_files, key=lambda x: x["height"])["link"]
            path = f"clip_{i}.mp4"
            i += 1

            try:
                with open(path, "wb") as f:
                    f.write(requests.get(link, timeout=20).content)
                
                clip = VideoFileClip(path)
                # Bozuk veya 0 saniyelik videoları atla
                if clip.duration > 0.5:
                    current += clip.duration
                    paths.append(path)
                clip.close()
            except Exception as e:
                print(f"Video indirme hatası: {e}")
                continue

    return paths

# --- ALTYAZI ---
def make_subtitles(text, duration):
    font_path = get_font()
    try:
        font = ImageFont.truetype(font_path, 70)
    except:
        font = ImageFont.load_default()

    words = text.split()
    chunks = []
    temp = []
    # Kelimeleri 2-3'lü gruplara böl
    for w in words:
        temp.append(w)
        if len(temp) >= 2:
            chunks.append(" ".join(temp))
            temp = []
    if temp:
        chunks.append(" ".join(temp))

    if not chunks: return None

    per = duration / len(chunks)
    clips = []

    for ch in chunks:
        img = Image.new("RGBA", (W, H), (0, 0, 0, 0))
        draw = ImageDraw.Draw(img)

        # Metni sar (wrap)
        wrapped = "\n".join(textwrap.wrap(ch.upper(), 15))
        
        # Text boyutunu hesapla
        bbox = draw.textbbox((0, 0), wrapped, font=font)
        tw = bbox[2] - bbox[0]
        th = bbox[3] - bbox[1]

        x = (W - tw) // 2
        y = int(H * 0.75) # Alt kısma yakın

        # Siyah arka plan
        draw.rectangle([x-20, y-20, x+tw+20, y+th+20], fill=(0,0,0,160))
        # Beyaz yazı, kalınlık efekti için hafif kaydırma yapılabilir ama basit tutuyoruz
        draw.text((x, y), wrapped, font=font, fill="white", align="center")

        clips.append(ImageClip(np.array(img)).set_duration(per))

    return concatenate_videoclips(clips, method="compose")

# --- CLIP DÜZELT ---
def prepare_clip(path):
    try:
        c = VideoFileClip(path)
        # Sesi kaldır (Pexels videoları bazen sesli olabiliyor)
        c = c.without_audio()
        
        # Dikey formata zorla (9:16)
        if c.w / c.h > W / H:
            c = c.resize(height=H)
            c = c.crop(x_center=c.w/2, width=W, height=H)
        else:
            c = c.resize(width=W)
            c = c.crop(y_center=c.h/2, width=W, height=H)
            
        return c
    except:
        return None

# --- MONTAJ ---
def build_video(content_data):
    script = content_data["script"]
    
    # 1. Ses Oluştur
    asyncio.run(generate_tts(script, "voice.mp3"))
    if not os.path.exists("voice.mp3"):
        return None
        
    audio = AudioFileClip("voice.mp3")
    
    # 2. Videoları İndir
    paths = get_videos(audio.duration)
    if not paths:
        audio.close()
        return None

    # 3. Videoları İşle
    clips = []
    for p in paths:
        c = prepare_clip(p)
        if c:
            clips.append(c)

    if not clips:
        audio.close()
        return None

    # 4. Videoları Birleştir
    main = concatenate_videoclips(clips, method="compose")

    # Ses süresine eşitle
    if main.duration < audio.duration:
        # Eğer video kısa geldiyse döngüye al
        main = main.loop(duration=audio.duration)
    else:
        main = main.subclip(0, audio.duration)

    main = main.set_audio(audio)

    # 5. Altyazı Ekle
    subs = make_subtitles(script, main.duration)
    final = CompositeVideoClip([main, subs], size=(W, H)) if subs else main

    out = "final_video.mp4"
    final.write_videofile(
        out,
        codec="libx264",
        audio_codec="aac",
        fps=FPS,
        threads=2,
        preset="ultrafast" # Hız için
    )

    # Temizlik
    for c in clips: c.close()
    audio.close()
    main.close()
    final.close()
    
    # İndirilen klipleri sil
    for p in paths:
        if os.path.exists(p):
            os.remove(p)

    return out

# --- TELEGRAM ---
@bot.message_handler(commands=["video"])
def handle_video(message):
    args = message.text.split(maxsplit=1)
    if len(args) < 2:
        bot.reply_to(message, "Bir konu yaz: /video horror story")
        return

    topic = args[1]
    bot.reply_to(message, "🎬 Video senaryosu ve kurgusu hazırlanıyor, bu 1-2 dakika sürebilir...")

    # İçeriği çek
    content = get_content(topic)
    
    # Eğer API hatası varsa ve script kısa ise loglarda görürüz
    if len(content["script"].split()) < 20:
        bot.send_message(message.chat.id, "⚠️ Uyarı: Hikaye çok kısa oluşturuldu, API anahtarlarını kontrol et.")

    path = build_video(content)

    if path and os.path.exists(path):
        # Caption hazırlama
        caption_text = (
            f"🎬 **{content['title']}**\n\n"
            f"{content['description']}\n\n"
            f"{content['hashtags']}"
        )
        
        with open(path, "rb") as v:
            bot.send_video(
                message.chat.id, 
                v, 
                caption=caption_text, 
                parse_mode="Markdown"
            )
    else:
        bot.reply_to(message, "❌ Video oluşturulurken bir hata oluştu.")

print("Bot çalışıyor...")
bot.polling(non_stop=True)

